### ISSUE TITLE
Crash reporting system

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-editor#107]
Now we have simple dialog saying that editor crashed, it should be replaced by crash reporter which would allow to quickly access log file and more importantly allow to upload crash file to my server.

There is also "Internal exception occurred" toast, it should be also possible to report those exceptions.

**Comment by kotcrab** [comment]
Main crash reporter was added. Next is support for internal exceptions.

**Comment by junkdog** [comment]
if you don't already having something similar, I can recommend the git-commit-id-plugin; the generated properties file attached to our crash logs, pretty convenient.

```xml
<plugin>
    <groupId>pl.project13.maven</groupId>
    <artifactId>git-commit-id-plugin</artifactId>
    <version>2.2.0</version>
    <executions>
        <execution>
            <goals>
                <goal>revision</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>

        <!-- that's the default value -->
        <dateFormat>yyyy-MM-dd.MM HH:mm:ss</dateFormat>
        <!-- ALTERNATE SETUP - GENERATE FILE -->
        <!--
            If you want to keep git information, even in your WAR file etc,
            use this mode, which will generate a properties file (with filled out values)
            which you can then normally read using new Properties().load(/**/)
        -->

        <!-- this is false by default, forces the plugin to generate the git.properties file -->
        <generateGitPropertiesFile>true</generateGitPropertiesFile>

        <!--
            The path for the to be generated properties file, it's relative to ${project.basedir}
            The default value is ${project.build.outputDirectory}/git.properties
        -->
        <generateGitPropertiesFilename>
            ${project.build.outputDirectory}/git.properties
        </generateGitPropertiesFilename>
    </configuration>
</plugin>
```

**Comment by kotcrab** [comment]
We are using Gradle now so no Maven plugins for us. We have something similar, there is build timestamp although that haven't proven useful yet.

**Comment by junkdog** [comment]
> We are using Gradle

duh... it completely escaped my mind.

**Comment by kotcrab** [comment]
Yeah it's recent thing so you could have missed that, I must say it's nice change after xml hell.

**Comment by kotcrab** [comment]
Internal exception reporting added, all done.
