### ISSUE TITLE
Spritesheet animations support

### ISSUE THREAD

**Issue by omomthings** [kotcrab/vis-editor#111]
Why not consider adding Atlas texture in 0.3.1, more powerful  than simple sprites and way more simple than spine. Maybe add an atlas texture folder like for particles, and put there the corresponding files.. what do you think about it @kotcrab  ?

**Comment by kotcrab** [comment]
Atlases are already supported. See https://github.com/kotcrab/VisEditor/wiki/Adding-assets-to-your-project:
>atlas - add your texture atlases here, each atlas must coexist of two files: .atlas and .png file. To create texture atlases you should use this free tool. Note: you should use texture atlases when you already have them and don't want to unpack them. VisEditor automatically packages assets from gfx folder into texture atlas.

**Comment by omomthings** [comment]
Excuse me I wasn't talking about atlas files in general, I meant animation using atlas file, as the editor is made on top of the libgdx library, I guess that it would not be pretty hard to use this system.. as a said an animation using is easier using atlas animations than spine of spriter animations..

**Comment by kotcrab** [comment]
Ah you meant sprite animation, yeah I agree, it should be added.
