### ISSUE TITLE
Migrate to Gradle build system

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-editor#121]
Will be done after VisUI 1.0.0 but I still needs to research this more. Jenkins configuration will need updating.

* [x] Update project files (#135) - this renamed all main folders (Editor, Runtime etc.) to lowercase which will break pretty much all links linking to files in this repository
* [x] Add Sonatype deployment - http://central.sonatype.org/pages/gradle.html

After merging `gradle` branch:
* [x] Update CI server configuration
* [x] Update wiki links
* [x] Update links inside project
* [x] Update building from source instructions
* [x] Rename repo name to vis-editor - Github will create auto redirect from `VisEditor`

**Comment by Favorlock** [comment]
PR I am currently working on:
#134

**Comment by Favorlock** [comment]
#134

**Comment by Favorlock** [comment]
#135

**Comment by kotcrab** [comment]
Alright, `gradle` branch have been merged. I renamed repo and updated all links in wiki and inside source files. CI server will be displayed until I update all build jobs configuration.

**Comment by kotcrab** [comment]
All done, thanks for your help @Favorlock.
