### ISSUE TITLE
Publish VisUIWebDemo Sources

### ISSUE THREAD

**Issue by Favorlock** [kotcrab/vis-editor#141]
Someone was asking where they can find the source code of the VisWebDemo. I couldn't find it with a quick look, so I'm assuming it hasn't been published.

**Comment by kotcrab** [comment]
It's [here](https://github.com/kotcrab/vis-editor/tree/master/ui/test/com/kotcrab/vis/ui/test/manual). I added link to the wiki so it's easier to find.
