### ISSUE TITLE
Text on viseditor sometimes drops and becomes uneditable

### ISSUE THREAD

**Issue by xtremetom** [kotcrab/vis-editor#145]
https://gyazo.com/3c88369a9a6c50901bdaa740fd783eb3

The text here was originally on the paper but after making a few more layers with text, it dropped here and can not be selected or editted.

**Comment by kotcrab** [comment]
What editor version are you using? Did that happen after loading scene or while editing? Is there reliable way to reproduce it?

**Comment by xtremetom** [comment]
version 0.3.0
I think it happened after loading and I have not been able to reproduce it. But if it happens again I will let you know.

**Comment by kotcrab** [comment]
0.3.1 fixed some text issue, might be related to that. You should update to 0.3.1.

**Comment by xtremetom** [comment]
Thanks Ill try it out
