### ISSUE TITLE
Export json error: Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by xtremetom** [kotcrab/vis-editor#148]
https://gyazo.com/ff53b9a32f75e801f047597e6edebc7a

Today I started to get this error while saving.

I have upgraded from 0.3.0 to 0.3.1

**Comment by kotcrab** [comment]
Please click details button and paste them here.

**Comment by xtremetom** [comment]
where do I find that button?

**Comment by kotcrab** [comment]
Look at your screenshot, it's next to Ok.

**Comment by xtremetom** [comment]
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 2 column 14 path $.viewport

com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
com.google.gson.Gson.fromJson(Gson.java:814)
com.google.gson.Gson.fromJson(Gson.java:752)
com.kotcrab.vis.editor.module.project.SceneIOModule.load(SceneIOModule.java:82)
com.kotcrab.vis.editor.module.project.SceneCacheModule.get(SceneCacheModule.java:42)
com.kotcrab.vis.editor.extension.DefaultExporter$ExportAsyncTask.lambda$exportScenes$236(DefaultExporter.java:258)
com.kotcrab.vis.editor.util.async.AsyncTask.lambda$executeOnOpenGL$91(AsyncTask.java:80)
com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:263)
com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:229)
java.awt.event.InvocationEvent.dispatch(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

Caused by: Expected a string but was BEGIN_OBJECT at line 2 column 14 path $.viewport

com.google.gson.stream.JsonReader.nextString(JsonReader.java:837)
com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:746)
com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:719)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
com.google.gson.Gson.fromJson(Gson.java:814)
com.google.gson.Gson.fromJson(Gson.java:752)
com.kotcrab.vis.editor.module.project.SceneIOModule.load(SceneIOModule.java:82)
com.kotcrab.vis.editor.module.project.SceneCacheModule.get(SceneCacheModule.java:42)
com.kotcrab.vis.editor.extension.DefaultExporter$ExportAsyncTask.lambda$exportScenes$236(DefaultExporter.java:258)
com.kotcrab.vis.editor.util.async.AsyncTask.lambda$executeOnOpenGL$91(AsyncTask.java:80)
com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:263)
com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:229)
java.awt.event.InvocationEvent.dispatch(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

**Comment by kotcrab** [comment]
This is an error you got on export, not on save. Can you load scene in editor normally? Is there a way to reproduce this? Please post header of your scene: open scene file in text editor, then copy until `layers` fields, eg:
```
{
  "versionCode": 2,
  "path": "/scene/test.scene",
  "width": 12.8,
  "height": 7.2,
  "pixelsPerUnit": 100.0,
  "viewport": "STRETCH",
  "physicsSettings": {
    "physicsEnabled": false,
    "gravityX": 0.0,
    "gravityY": 0.0,
    "allowSleep": false
  },
```

**Comment by xtremetom** [comment]
{
  "versionCode": 2,
  "path": "scene/game.scene",
  "width": 1280.0,
  "height": 720.0,
  "pixelsPerUnit": 1.0,
  "viewport": "EXTEND",
  "physicsSettings": {
    "physicsEnabled": false,
    "gravityX": 0.0,
    "gravityY": 0.0,
    "allowSleep": false
  },

The error occurs every time I try to export. I can still run the json created.

**Comment by kotcrab** [comment]
This look fine but this is export exception so this error may be about other scene file. I need more info. Get this snapshot build http://dl.kotcrab.com/vis/editor/edge/VisEditor-edge-20160323-1.zip then run export and if you get that error again then in editor press Help->Show Log then paste it on Gist or Pastebin. Don't paste it directly here since it will be long.

**Comment by xtremetom** [comment]
Done. Log was empty.

**Comment by kotcrab** [comment]
Ow, log isn't flushed to file before clicking Show Log, I'll fix that. Anyways, restart editor and it will be there.

**Comment by xtremetom** [comment]
Ok I see, the log makes the issues clear. Fixed it. 

I had a scene that had a json mistake. The mistake was a result of me toying with it. So no issue with viseditor, just me :)
