### ISSUE TITLE
Support for system font feature?

### ISSUE THREAD

**Issue by xeoshow** [kotcrab/vis-editor#150]
Hi,

Can we add support for the system font feature? Developers can specify the android or ios default system font and no ttf or .fnt related files needed.

Thanks!

**Comment by kotcrab** [comment]
I don't know see how that would work. What about desktop and html platforms? You can't access platforms apis without [interfaces](https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code) which would complicate everything. Even if you do this how do you obtain system font and create `BitmapFont`? Too much trouble for little gain imho. Please use forum for feature requests next time.
