### ISSUE TITLE
Text on viseditor sometimes drops and becomes uneditable

### ISSUE THREAD

**Issue by xtremetom** [kotcrab/vis-editor#152]
I previously mentioned this issue with no way to replicate but I have since found a way.

If I have the layer with text visible when I exit viseditor then that text remains in position upon the following opening.

Any other layer with text that was hidden when viseditor was closed is all messed up when I open it up again.

https://gyazo.com/e8e35332e1b84d1239d268ddda6a20ad
https://gyazo.com/f45f66041986392f8f541b70d357d3c9

Hope that helps

**Comment by kotcrab** [comment]
Thanks for reproduction steps, I can reproduce in 0.3.1 using this method however I can't reproduce in 0.3.2-SNAPSHOT so I guess I fixed this already, probably in commit https://github.com/kotcrab/vis-editor/commit/bef3e9b537470e09bd8e731017a1714386bcf39d.

**Comment by xtremetom** [comment]
Yep quick play with 0.3.2, it seems the issue is fixed :)
