### ISSUE TITLE
VisText not treated the same as other Entities

### ISSUE THREAD

**Issue by xtremetom** [kotcrab/vis-editor#155]
I only post this as a bug rather than on the forum because I remember you saying they should both act the same.

In the linked project ([here](https://github.com/xtremetom/Fade-Test)) I have created a 3 layered game. All layers have 1 coin and 1 text entity. The button in the middle simply changes the current layer being viewed and add/removes invisible accordingly.

This process works perfectly for the coins but the text only works if all layers start as visible.

**Comment by xtremetom** [comment]
https://gyazo.com/c40f66e8e51a282c903b8064e1d1f755
https://gyazo.com/3c42b5539461710a5151874ad3d19a8a

**Comment by kotcrab** [comment]
Fixed in `0.3.2-SNAPSHOT`, thanks.
