### ISSUE TITLE
How to use VisScrollPane?

### ISSUE THREAD

**Issue by ks3dev** [kotcrab/vis-editor#156]
Hello, I didn't find the demo,  could u send me the link?

**Comment by kotcrab** [comment]
This is a issue tracker not help board. Use forums or IRC if you need help.
The demo source code link is in the wiki. VisScrollPane test is here: https://github.com/kotcrab/vis-editor/blob/master/ui/test/com/kotcrab/vis/ui/test/manual/TestTextAreaAndScroll.java
