### ISSUE TITLE
NumberSelector rounds large numbers

### ISSUE THREAD

**Issue by ip** [kotcrab/vis-editor#159]
``` Java
NumberSelector selector = new NumberSelector(
        "number selector:", Integer.MAX_VALUE,  Integer.MIN_VALUE,  Integer.MAX_VALUE, 1);
```
Try read from such number selector. NumberSelector.getValue() should return int instead of float. This is because of float representation. If you are unfamiliar with it, please read the article on Wikipedia. In short, the longer float value is from zero, the bigger rounding error is.

Maybe I'll submit pull request later. Please lets fix it, because I wouldn't want to recreate my own version of this control. By the way, thanks for great library, it makes things easier.

**Comment by kotcrab** [comment]
Unfortunately selector has to allow entering float values so returning int is no an option. Fixing this will probably require adding two separate implementation for int and float with common parent class.

**Comment by ip** [comment]
Maybe add getIntValue() method then?

**Comment by kotcrab** [comment]
That would just cast float to int. Note that this also affects other values (`min`, `max`) since they are all stored as floats.

**Comment by ip** [comment]
Yeah, you are right. Then I think the most nice solution would be to change floats to doubles for this class - it even won't break backwards compatibility.

**Comment by ip** [comment]
Regarding getIntValue() I mean not just `return getValue()` of course, but parse text field as integer.

**Comment by kotcrab** [comment]
This sounds ok, do you want to send PR for it?

**Comment by ip** [comment]
@kotcrab Sorry, I decided to use OpenSceneGraph instead of LibGDX for my project :smile:

**Comment by kotcrab** [comment]
`NumberSelector` is going to be replaced by `Spinner` which can use be used together with `FloatSpinnerModel` to support `BigDecimal`.
