### ISSUE TITLE
MenuItem returns null stage on ClickListener

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#160]
Try adding a `MenuItem` with a `ClickListener` that prints its `Stage`. `null` will be returned each time. It would seem sensible to return `Stage` from the menus that the item is currently in (recursively, returning the first found stage instance) if the it is not set internally. After all, the item itself is *added* to the stage - but simply not shown just yet. (But, in this case, the item ***is*** shown, as you can click it - and it still seems to have no stage.)

See https://github.com/czyzby/gdx-lml/issues/13.

**Comment by kotcrab** [comment]
This [SSCCE](https://gist.github.com/kotcrab/bb3ea1e1bed81fb0d291cb5da92ae6d6) prints `clicked, stage null: false`. Perhaps I don't understand something but it seems to work correctly, when the listener is called menu is still added to stage so it isn't null.

**Comment by czyzby** [comment]
`gdx-lml-vis` also uses `addItem` and `addMenu` methods to create menus, but the `MenuItem` reports a `null` stage. I added a workaround on my part, not sure what to suggest to reproduce this issue other than trying to use `gdx-lml-vis-tests` project.

Add this method in `MainView`:
```
    @LmlAction("print")
    void print(final MenuItem item) {
        System.out.println(item.getStage());
    }
```
Copy and parse this template, try clicking on the item:
```
<menuBar>
  <menu text="menu">
    <menuItem>submenu
      <subMenu>
        <menuItem onClick="print">item
        </menuItem>
      </subMenu>
    </menuItem>
  </menu>
</menuBar>
```
As I've said, `gdx-lml-vis` seems to be using the standard API, so either there is some weird bug in LML or you haven't considered a corner case. Maybe try adding `root` to `Stage` *after* `menuBar` is already in it?

**Comment by kotcrab** [comment]
After moving that line it still works. 

I added `System.out.println(item.getStage());` in render. Looks like as long MenuItem is visible in stage, `item.getStage()` is not null. Right after clicking it, menu gets auto removed and it prints null again which is expected. I don't think I missed something, after all stage (un)setting is managed by libgdx.

I haven't tried reproducing with `gdx-lml-vis-tests` yet.

**Comment by czyzby** [comment]
> I don't think I missed something, after all stage (un)setting is managed by libgdx.

That's what I thought, so I was pretty much surprised to see this kind of bug. Not sure what's causing this, as LML seems to properly use menus API and the items are properly rendered on the screen. See https://github.com/czyzby/gdx-lml/issues/13#issuecomment-209687239

**Comment by kotcrab** [comment]
For some reason lml method is called after item has it's stage set to null. In my sscce it is called before that. Initially I thought this was because of using submenu but that's not it. I don't know, I can't reproduce it with just VisUI.

**Comment by czyzby** [comment]
I'm just guessing here, but you could try the following order before we give up on this:
- Add menu to table.
- Add item to menu.
- Add table to stage.

**Comment by czyzby** [comment]
Nope, I tried both and still nothing. Replacing `ChangeListener` with `ClickListener` has the same result. Not sure what's causing this. The workaround on my end should be enough for `gdx-lml-vis` users, and I don't think it affects the rest.

By the way, when using `ChangeListener` in `lml`, the correct stage seems to be reported. This is some weird issue with listeners order (I think).

Adding some note about preferring `ChangeListeners` over `ClickListeners` in `MenuItem` docs should be enough. I think this issue can be closed.

**Comment by kotcrab** [comment]
`ChangeListener` should always be preferred for every subclass of `Button` otherwise you don't support `setDisabled`. `ClickListener` doesn't care about it.

This can be related to listener order, lml listener is called right after `item.setStage(null)` was called by libgdx.

I'll update docs.

**Comment by czyzby** [comment]
> `ChangeListener` should always be preferred for every subclass of `Button` otherwise you don't support `setDisabled`.

I know, but you got to admit that `ClickListener` seems more fitting (judging by its name) for all clickable widgets. I'm pretty sure this was the one that I usually used when I was just starting with LibGDX. In this case, we're got more to worry about that just the disabled status, so I think the javadoc note was justified.

**Comment by kotcrab** [comment]
Unfortunately it's more fitting. I've seen issues people have then they used `ClickListener` and were reporting than they still get events for disabled buttons.
