### ISSUE TITLE
FloatingGroup children ignore size settings

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#161]
Consider the following code:

```
        final FloatingGroup group = new FloatingGroup(200f, 200f);
        final VisImage image = new VisImage(VisUI.getSkin().getDrawable("button"));
        image.setX(10f);
        image.setY(10f);
        image.setWidth(100f);
        image.setHeight(100f);
        group.addActor(image);
        getStage().addActor(group);
```
Instead of drawing a 100x100 image, this is shown:
![floating](https://cloud.githubusercontent.com/assets/11707612/14587881/53076796-04bb-11e6-9d06-2151c12e6f77.png)
(`X2` skin is used, so this is basically a raw drawable.)

Changing `x` and `y` does work, but setting the size - doesn't. Same thing applies to `VisTextButton`, for example. While the values seem to properly set in actor objects, they are simply ignored. You could modify rendering method to make `FloatingGroup` children honor these values - kind of like `Table` does with its cell size attributes.

Also, `prefWidth` and `prefHeight` from `FloatingGroup` cannot be set in runtime once the object is created - adding `setPrefWidth/setPrefHeight` or setting these values in overridden `setWidth/setHeight` (or - even better - both) would be nice.

(By the way - a `VisImage(String)` constructor that extracts drawables directly from VisUI skin would be nice.)

**Comment by kotcrab** [comment]
I ended up adding option to use children preferred size, this basically applies to every instance of `Layout`. `setWidth()` and `setHeigth()` would not have effect for them.

I'm not sure about overriding `setWidth()` and `setHeigth()` to change `prefSize`. There are few more methods that change size and it doesn't seem like a nice solution.

Added `VisImage` construtor.

**Comment by czyzby** [comment]
> I'm not sure about overriding `setWidth()` and `setHeigth()` to change `prefSize`. There are few more methods that change size and it doesn't seem like a nice solution.

Are you sure, though? It seems like the `prefWidth` and `prefHeight` should match current width. Actually, now that I think about it, you could completely remove these variables and return `getWidth` and `getHeight` for as pref sizes. This might require some testing, but I think it actually might be the right solution, considering most people will probably want such groups in tables anyway, and the most natural way of setting widget sizes with `Table` API is using the `width(float) and `height(float)` methods.

**Comment by kotcrab** [comment]
`setSize`, `sizeBy` (2 variants) and `setBounds`. Now, looking at implementation of `WidgetGroup` it should work when `getWidth/Height` is returned for preferred size, I'll test it.

**Comment by kotcrab** [comment]
Yep, works fine and size can be nicely overridden by table if needed (`table.add(group).size(...)`).

**Comment by kotcrab** [comment]
Unfortunately looks like my implementation with `prefWidth/Height` was more valid. When expand/fill is used on table. If you maximize it will take all available size (`prefWidth/Height` will return max size) but then if you minimize it, `prefWidth/Height` won't change to lower value and table layout will break because group will be too big to fit.

**Comment by czyzby** [comment]
I see. Don't forget the setters, though - I think these values should be modifiable at runtime.

By the way, it basically affects only resizeable widgets. You could make these values optional by keeping `getPrefWidth()` implemented kind of like this: `return prefWidth <= 0f? getWidth() : prefWidth`.

**Comment by kotcrab** [comment]
> By the way, it basically affects only resizeable widgets. You could make these values optional by keeping getPrefWidth() implemented kind of like this: return prefWidth <= 0f? getWidth() : prefWidth.

I'll do that but I think no-arg constructor should keep those values at 0, it will be most commonly used when you want to create group added to table with `grow()` (`add(new FloatingGroup()).grow()`)

**Comment by kotcrab** [comment]
Well in that case it should be `prefWidth < 0f` and `-1` would be returning `getWidth()`
