### ISSUE TITLE
Is there a way to create an alias in USL?

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#162]
This is a valid JSON Skin definition:

```
com.badlogic.gdx.graphics.Color: {
	green: {a: 1, b: 0, g: 1, r: 0 },
	green-alias: green
}
```
The same color will be accessible through `green` and `green-alias`. I understand that you can use `inherits` in USL to generate two equal styles, but can you use actual aliases? Trying a similar trick in USL currently results in broken JSON files.

**Comment by kotcrab** [comment]
This is parsing issue, I'll fix this.
