### ISSUE TITLE
VisValidatableTextField should report as valid when disabled

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#163]
When a user is asked to fill a form, he should be "punished" for being unable to modify disabled widgets. Disabled check boxes or text fields **can be used in forms** to show default settings (or settings editable only under certain conditions) - in such case, the application *creator* should make sure that the data is valid, and field validation should be turned off, as the *user* has no way to change the data.

Current implementation ignores the disabled status - a form with disabled, unfillable fields still reports as full of errors, even though the user is pretty much stuck in such situation.

**Comment by kotcrab** [comment]
I've implemented this at `FormValidator` level and made it the default behavior. Plus I've changed `VisCheckBox` and `VisTextFiled` to now draw error border when they are disabled.
