### ISSUE TITLE
Validation not always fired

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#165]
There seems to be a bug with `VisValidatableTextField` and forms when "changing" its value to, well, the same value - form is not refreshed, so even if the data is currently valid, error message will still be displayed.

Reproduction:
- Add text field with empty directory filter.
- Choose a non-empty directory with file chooser, set directory path as field content.
- Delete the content of non-empty directory.
- Choose the same directory again, set as field content.
- Form still displays the error, yet field no longer has the error border.

See example below. Text field now contains path to a valid directory and no longer has error border, yet error message is still displayed. Changing any field included in form fixes this issue, but the refresh should be automatic, not manual. 
![Invalid form](https://cloud.githubusercontent.com/assets/11707612/14943289/ca23f44c-0fd4-11e6-891c-ac6fa9dd47c4.png)

**Comment by kotcrab** [comment]
Can confirm, this is a bit troubling, `VisTextField` (the same would go for `TextField`) does not consider changing the text to the same one as it was before as actual change so it doesn't send change event. Which doesn't trigger change listener added by form validator and form status isn't updated.

`(Vis)TextField#setText`:
```java
public void setText (String str) {
	if (str == null) str = "";
	if (str.equals(text)) return;
	//...
}
```

`VisValidatableTextField` performs validation regardless of that so its status is updated correctly.

**Comment by czyzby** [comment]
Well, you could either always fire change events in your overridden `setText` method (after all - user requested to *change* the content) or add a boolean setting that allows you to decide whether change events should be fired. Something like `alwaysFireChangeEvent`, although you could go for something less verbose.

**Comment by kotcrab** [comment]
Alright done, I added VisTextField property for controlling this. It should work now, no change is needed on your side.

**Comment by czyzby** [comment]
Except it's `true` by default (which is reasonable, as it matches old behavior), so I *do* have to change text field settings. ;) Still, thanks for the quick fix.

**Comment by czyzby** [comment]
I can confirm that forms work as expected when this property is set to `false`.

**Comment by kotcrab** [comment]
Yes it's `true` for `VisTextField` to match old behavior but `VisValidatableTextField` sets it to false as default. See `VisValidatableTextField#init`.

**Comment by czyzby** [comment]
Oh, I see, I haven't checked out the whole commit. Now that I think about it, that seems to be the correct approach. Thanks.
