### ISSUE TITLE
Values are not properly truncated after scale change in Spinner with BigDecimal model

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#166]
Reproduction:
- Construct a `Spinner` with `FloatSpinnerModel` with scale of `2` and value of `1.5`.
- Change the scale to `1`.
- Text field's value will be `1.50`, the error border will be displayed.

**Comment by kotcrab** [comment]
I'll look more into this tomorrow but from quick check it looks like model is not notyfing spinner to update value. May also affect other models

**Comment by czyzby** [comment]
Can confirm the value is properly updated using the default `Spinner` settings.
