### ISSUE TITLE
VisUI skin does not have styles for ImageButton and ImageTextButton

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#167]
Default `ImageButtonStyle` and `ImageTextButtonStyle` are missing. For completeness, they could be included in the skin (with drawables matching their VisUI widget equivalents). While not necessary and arguably undesired (more overhead at runtime, bigger JSON file), this should be considered if VisUI aims to provide styles for 100% of standard Scene2D widgets. Note that styles for actors with VisUI equivalents (like `TextButton`) are currently included.

**Comment by kotcrab** [comment]
VisUI skin was created based on default scene2d.ui skin. If there is no styles for some widget, the reason is it wasn't there in the original skin. That said though I agree with you, the most basic ones styles could be added for those widgets.

**Comment by kotcrab** [comment]
I added default styles but to be honest `ImageButton` is lacking constructors to make them useful.
In case of VisUI there is `ImageButton` constructor which clones default style and adds supplied image to it, very useful.

**Comment by czyzby** [comment]
Well, it's nice to have a default style for every Scene2D widget out there, even if most of them can be simply deleted with no harm done.

Now that I think about it, an "optimized" VisUI skin with no "duplicates" would be nice. A rule of thumb - if VisUI has an equivalent or improved version, its style should not be included in the minified skin. If would be sufficient for most applications, and would discourage usage of standard inferior Scene2D widgets.

**Comment by kotcrab** [comment]
> and would discourage usage of standard inferior Scene2D widgets.

Or it would lead to anger that there is no support for scene2d.ui widgets. Best course of action would to be merge VisUI changes into libgdx but that's rather impossible. Especially with focus borders which I'm quite sure would be very unlikely to be merged. (also it would take forever to review ;D)

Those extra styles does not require additional assets so it isn't that big of a problem to include them. Making multiple version would be quite simply using USL and `include <>` but that would rise complexity and increase library size if those optimized styles would be included in release jar.

**Comment by czyzby** [comment]
Point taken. ; )
