### ISSUE TITLE
Including VisEditor toasts in VisUI?

### ISSUE THREAD

**Issue by jpsgamboa** [kotcrab/vis-editor#168]
`VisEditor`'s [toasts](https://github.com/kotcrab/vis-editor/blob/ac813ad180b4b466c887e7af433637b9c4eaf129/editor/src/com/kotcrab/vis/editor/module/editor/ToastModule.java) are very neat. Seeing as we have [Dialogs](https://github.com/kotcrab/vis-editor/blob/master/ui/src/com/kotcrab/vis/ui/util/dialog/Dialogs.java) in VisUI, why not also include toasts?
The class is easy to recreate, but I bet toasts can be useful to anyone who uses VisUI.

**Comment by kotcrab** [comment]
That's a good idea, in the past there were some features that started in editor and was later moved to ui, eg. tabbed pane. While we are at it they might be some other classes that worth be moving to UI.

**Comment by jpsgamboa** [comment]
Nice. I actually found out about toasts by searching for them here, assuming you'd have made something of the sort. So it would be nice to have some other things exposed here.

**Comment by kotcrab** [comment]
Ok, here is a list of what is worth considering moving to UI:
- Toasts
-  `AsyncTask API` and `AsyncTaskProgressDialog`
- `VisChangeListener` - allows to use ChangeListener with lambdas, perfect for Java 8 users
- `EnumSelectBox` - select box for enums, support custom enum names
- `ProgressImage` - spinning image with round progress icon
- `IndeterminateCheckbox` and `IndeterminateTextField` - checkbox and text field that can be set into indeterminate mode. Unlikely though, implementation is pretty specific.

**Comment by kotcrab** [comment]
Done, see [TestToats](https://github.com/kotcrab/vis-editor/blob/master/ui/test/com/kotcrab/vis/ui/test/manual/TestToasts.java) for some examples. I created https://github.com/kotcrab/vis-editor/issues/174 for other VisEditor classes.
