### ISSUE TITLE
TabbedPane's Table has no direct access to pane's instance

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#169]
While it's not exactly a bug, it would be nice if `TabbedPane` stored a `TabbedPaneTable` with a reference to the pane - kind of like `ListView` does with `ListViewTable`. Currently there's no way to access `TabbedPane` when all you have is the table, and accessing specific cells (like the ones storing separator or drag pane) is problematic. Having access to `TabbedPaneTable` that providers getters of important `TabbedPane` cells would allow to fully customize the widget with ease.

**Comment by kotcrab** [comment]
I understand the thing about getting access to `TabbedPane` from `TabbedPaneTable`. I don't get the accessing specific cells part, the tabbed pane's `mainTable` will have only two cells, one with `DragPane` and one with separator. Do you think it's worth providing explicit getters for those?

**Comment by czyzby** [comment]
Well, Scene2D [sometimes does that](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ImageButton.java#L96). I don't see why you shouldn't include these, although `TabbedPane` getter will certainly be enough.
