### ISSUE TITLE
Wrong sprite size in VIsEditor

### ISSUE THREAD

**Issue by UvarovBoris** [kotcrab/vis-editor#170]
VisEditor-2.6-SNAPSHOT 
1) Add atlas with sprites in vis atlas directory
2) Add some object from atlas to scene
3) Change art in atlas. Replace sprite that was 200x200 in atlas, to another 300x100
In VisEditor size of prev added object dont change (200x200), so 300x100 distort to 200x200.
If delete old object and drag new size is right (300x100).

**Comment by kotcrab** [comment]
This is expected, the size is stored in scene file. If you replace the asset then the size in scene file won't be updated. Updating it automatically after asset has changed is not an option. Although size properties isn't currently exposed in editor in the future it might be also you must consider that size might be changed by user in the file directly.
