### ISSUE TITLE
NPE when deleting a folder in FileChooser

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#178]
> Exception in thread "LWJGL Application" java.lang.NullPointerException
> 	at com.kotcrab.vis.ui.util.dialog.Dialogs.showErrorDialog(Dialogs.java:160)
> 	at com.kotcrab.vis.ui.util.dialog.Dialogs.showErrorDialog(Dialogs.java:146)
> 	at com.kotcrab.vis.ui.widget.file.internal.FilePopupMenu$1$1.yes(FilePopupMenu.java:74)
> 	at com.kotcrab.vis.ui.util.dialog.Dialogs$OptionDialog$1.changed(Dialogs.java:364)
> 	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
> 	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
> 	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
> 	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
> 	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
> 	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

This exception was thrown after trying to delete a non-empty folder in the `FileChooser` on Linux Mint.

**Comment by kotcrab** [comment]
That wouldn't happen if you were using `JNAFileDeleter` ;)
