### ISSUE TITLE
FileChooser tries to create folder twice when pressing enter multiple times

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#191]
Reproducing the error:

- Open file chooser.
- Click new directory button.
- Choose a name.
- Quickly press enter key multiple times.
- Directory will be created and an error dialog with *"Directory with that name already exists"* message will be displayed.

This is definitely not a severe bug, but I don't think that's the expected behavior either.

**Comment by kotcrab** [comment]
Should be working now.
