### ISSUE TITLE
NPE: VisUI: FileChooser

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#195]
Was deleting files from a folder (right clicking selecting delete) and attempted to delete the last item in the folder and received a NPE.

Relaunching and deleting the last file inside the filechooser did work.

2016-06-19 20:04:25:0445 ERROR Thread[LWJGL Application,5,main]
  Stack trace:java.lang.NullPointerException
    com.kotcrab.vis.ui.widget.PopupMenu.showMenu(PopupMenu.java:255)
    com.kotcrab.vis.ui.widget.file.FileChooser$FileItem$1.touchUp(FileChooser.java:1583)
    com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
    com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
    com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
    com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

Edit: Forgot a bunch of useful information...

VisUI 1.1.1
Java 1.8.0_66

**Comment by kotcrab** [comment]
Thanks for reporting.
