### ISSUE TITLE
ColorPicker sending old color to ColorPickerListener instead of new color

### ISSUE THREAD

**Issue by KiwiTrinsic** [kotcrab/vis-editor#196]
When clicking on a color picker widget to change the color, the ColorPickerListener is being given the previous color rather than the newly selected on in changed(Color color). 

This appears to be caused by lines 324 and 325 in BaseColorPicker.java being in the wrong order. updateValuesFromHSVFields() should be called before updateUI() so as to place the new color in the color field before sending it to the listener. That is the order used in ExtendedColorPicker.java lines 246 and 247.

**Comment by kotcrab** [comment]
Good catch, thanks!
