### ISSUE TITLE
VisUI: FileChooser empty array crash

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#199]
Encountered on 1.1.4-SNAPSHOT

  Stack trace:java.lang.IllegalStateException: Array is empty.
    com.badlogic.gdx.utils.Array.first(Array.java:311)
    com.kotcrab.vis.ui.widget.file.FileChooser.getFileListFromSelected(FileChooser.java:749)
    com.kotcrab.vis.ui.widget.file.FileChooser.selectionFinished(FileChooser.java:662)
    com.kotcrab.vis.ui.widget.file.FileChooser.access$2500(FileChooser.java:76)
    com.kotcrab.vis.ui.widget.file.FileChooser$16.changed(FileChooser.java:592)
    com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
    com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
    com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
    com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
    com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
    com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
    com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
    com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
    com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
    com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by kotcrab** [comment]
Looks like you tried to use `FileTypeFilter` rule without providing any extension.
