### ISSUE TITLE
VisUI: FileChooser crashes if last used location no longer exists

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#200]
FileChooser was pointed at a removable drive, disconnected the drive (while the file chooser was closed) on next launch it crashed as the drive was no longer a valid path. (FileChooser.java:853) Ecountered on one of the 1.1.4-SNAPSHOT's.

(No full stack trace due to difficulty in copying the data at the moment).

**Comment by kotcrab** [comment]
Can't reproduce on 1.1.5-SNAPSHOT.

**Comment by WickedShell** [comment]
Reproduced on 1.1.5-SNAPSHOT

2016-07-23 15:33:29:0322 ERROR Thread[LWJGL Application,5,main]
  Stack trace:java.lang.IllegalStateException: Provided directory does not exist!
    com.kotcrab.vis.ui.widget.file.FileChooser$20.run(FileChooser.java:875)
    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)

Selected a file from a SD card (hit okay). The file chooser closed, removed the SD card from the computer then selected another button which requests the file chooser. As it is reusing the instance/trying to return to the last used folder which no longer is a valid path it crashes.

**Comment by kotcrab** [comment]
From your first post I assumed you meant crashing between app launches, that's why you should provide stacktrace and/or reproduction steps, anyways it's fixed now.
