### ISSUE TITLE
TabbedPane layout when tab content contains ScrollPane

### ISSUE THREAD

**Issue by code-disaster** [kotcrab/vis-editor#206]
I'm trying to show scrolling content inside a tabbed pane. If the scroll bar becomes visible, the tabs start to "leak" outside of their area, overlapping with other UI elements.

<img width="355" alt="screen shot 2016-08-05 at 17 05 11" src="https://cloud.githubusercontent.com/assets/4644167/17440887/d9116fe8-5b2e-11e6-9f9e-c3c3364d60de.png">

To illustrate the issue, I modified TestTabbedPane in the VisUI tests:

```
		public TestTab (String title) {
			super(false, true);
			this.title = title;

			VisTable scrollContainer = new VisTable();
			scrollContainer.left().top();

			for (int i = 0; i < 10; i++) {
				scrollContainer.add(new VisLabel(title + " # " + i)).row();
			}

			VisScrollPane scrollPane = new VisScrollPane(scrollContainer);
			scrollPane.setFlickScroll(false);
			scrollPane.setFadeScrollBars(false);
			scrollPane.setScrollingDisabled(false, false);

			content = new VisTable();
			content.add(scrollPane).left().top().expand().fill();
		}
```

Here's a diff patch: [scrolling-tabbedpane-patch.diff.zip](https://github.com/kotcrab/vis-editor/files/404017/scrolling-tabbedpane-patch.diff.zip)

**Comment by kotcrab** [comment]
For some reason `Table` has trouble doing layout for such configuration, maybe because ScrollPane expects to have its size set explicitly. Anyways you can fix this by forcing min height for tabs pane widget:
```java
add(tabbedPane.getTable()).minHeight(new PrefHeightIfVisibleValue()).growX();
row();
add(container).grow();
```

**Comment by code-disaster** [comment]
Thanks a lot, this fix works nicely.
