### ISSUE TITLE
Spinner doesn't fire change events on input

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#208]
I've spotted that unlike other input widgets, `Spinner` doesn't trigger `ChangeEvent` when you type anything in the field. `ChangeEvent` get fired only if one of the increment/decrement buttons has been pressed or user hit Enter.

There is no any ability to switch that behavior.

Simple fix could look like this (`IntSpinnerModel` for example):
```java
@Override
public void textChanged () {
	String text = spinner.getTextField().getText();
	if (text.equals("")) {
		current = min;
	} else if (checkInputBounds(text)) {
		current = Integer.parseInt(text);
        spinner.notifyValueChanged(true); // <--- here it is
	}
}
```

**Comment by kotcrab** [comment]
This behaviour now can be configured. Use `TextFieldEventPolicy.ON_KEY_TYPED` to get event on every entered key.

**Comment by metaphore** [comment]
Awesome, thanks!
