### ISSUE TITLE
Undo/Redo function

### ISSUE THREAD

**Issue by TommiK** [kotcrab/vis-editor#210]
It would be very useful to have an undo/redo function in the editor.
To implement it one could use command pattern.

**Comment by kotcrab** [comment]
Undo and redo are available since very beginning.
![2016-08-20_1449](https://cloud.githubusercontent.com/assets/4594081/17831316/576b7f48-66e5-11e6-94e2-cf288316ae42.png)

**Comment by TommiK** [comment]
Oh i was blind...short cut didn't work because of my keyboard layout. Sorry
