### ISSUE TITLE
VisUI: Filechooser StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#211]
Had a user encounter a index out of range while typing in the filechooser to name a new file to save.

2016-08-22 11:51:50:0562 ERROR Thread[LWJGL Application,5,main]
  Stack trace:java.lang.StringIndexOutOfBoundsException: String index out of range: 7
    java.lang.String.substring(Unknown Source)
    com.kotcrab.vis.ui.widget.VisTextField.insert(VisTextField.java:520)
    com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyTyped(VisTextField.java:1218)
    com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:49)
    com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
    com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
    com.badlogic.gdx.scenes.scene2d.Stage.keyTyped(Stage.java:445)
    com.badlogic.gdx.InputMultiplexer.keyTyped(InputMultiplexer.java:84)
    com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:318)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by kotcrab** [comment]
VisUI version? Possibly fixed in https://github.com/kotcrab/vis-editor/commit/190e8fd710d4b32973eeda1b35bd4e6e236e4071.

**Comment by WickedShell** [comment]
Knew I forgot something, was too tired :)

Version 1.1.5

**Comment by kotcrab** [comment]
I just released 1.1.6, I'm quite sure this is fixed in https://github.com/kotcrab/vis-editor/commit/190e8fd710d4b32973eeda1b35bd4e6e236e4071 (I saw similar stacktrace when fixing it).
I'm afraid I can't do much more without reproduction steps.

**Comment by WickedShell** [comment]
Sounds good thanks! I'm in the field at the moment and can't close it, but
feel free to close it.
