### ISSUE TITLE
Can't see negative symbol on spinners

### ISSUE THREAD

**Issue by francogp** [kotcrab/vis-editor#214]
Negative values don't display the symbol "-" like in this screenshot
https://www.dropbox.com/s/az6hnr2ew3s381z/Captura%20de%20pantalla%202016-09-02%2002.05.27.png?dl=0
* I configured the model to support values from -10_000 to 10_000
* I use SimpleFloatSpinnerModel with precision 3.

**Comment by kotcrab** [comment]
Thanks.
