### ISSUE TITLE
VisUI: LinkLabel add ctor for text url style

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#216]
Was extremely surprised to see that the only constructors for creating a LinkLabel with a provided style only accept the text string, and not a url. A constrcutor of LinkLabel(java.lang.CharSequence text, java.lang.CharSequence url, LinkLabel.LinkLabelStyle style) would be greatly appreciated! (I know that at the moment I can create it, then promptly set the target URL, but this is less elegant, and stands out for not supporting this.

**Comment by kotcrab** [comment]
Added, sorry for the delay.
