### ISSUE TITLE
Missing copy constructors in widget style classes

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#217]
- [x] `MenuStyle`
- [x] `MenuBarStyle` (Note that this style features only a single `Drawable` - copy constructor might still be nice "just in case", but is not crucial.)
- [x] `SeparatorStyle`
- [x] `SpinnerStyle`
- [x] `ToastStyle`
- [x] `TooltipStyle`
- [x] `VisSplitPaneStyle`, `MultiSplitPaneStyle`

Additionally:

- `ColorPickerStyle` does only a shallow copy of `ColorPickerWidgetStyle`. It would make sense to copy it completely with `this.pickerStyle = new ColorPickerWidgetStyle(other.pickerStyle);`.
- `Sizes` class does not have a copy constructor. While not your usual widget style and might not be copied very often, including another constructor for completeness would be reasonable.
- `ToastStyle` seems to reference a style by name (stored as string in `closeButtonStyleName`) instead of having a direct object reference to `XxxButtonStyle` instance, as usual in LibGDX styles.

**Comment by kotcrab** [comment]
Added, snapshot will be up soon.

> - `ToastStyle` seems to reference a style by name (stored as string in `closeButtonStyleName`) instead of having a direct object reference to `XxxButtonStyle` instance, as usual in LibGDX styles.

Is changing this really required? Aside from breaking compatibility I kind of disagree with libGDX approach here. Imo it makes more sense to reference style by name here. You would probably want to have the same looking close button in both tooltips and window. This allows to make cleaner skin with less duplication.

**Comment by czyzby** [comment]
It will not break JSON files, I think. This kind of style referencing by names is already handled by `Skin` loader - it might have a field with `ButtonStyle` instance under the hood in Java code, but in JSON you still can just use `buttonStyle: someExistingStyle` and it will just work. Well, as long as the style already exists in the skin.

**Comment by czyzby** [comment]
Well, to be honest, it isn't much of a problem, as people will usually use JSON skins based on your defaults anyway. If you think API change is not worth it, IMHO this issue can be closed.

**Comment by kotcrab** [comment]
> It will not break JSON files, I think. This kind of style referencing by names is already handled by Skin loader 

Nice, I didn't know about this. If that's the case then I'm ok with changing this. It will slightly break compatibility because I want to rename `closeButtonStyleName` to just `closeButtonStyle`.

**Comment by czyzby** [comment]
It seems that `BusyBarStyle` does not have a copy constructor as well. Sorry, missed that one.

**Comment by kotcrab** [comment]
No problem, added it.

**Comment by czyzby** [comment]
Thanks, styles API seems pretty much complete at this point.
