### ISSUE TITLE
Spinner$TextFieldEventPolicy is package private and cannot be used outside of a lib

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#219]
Since 1.1.6 `Spinner` has `Spinner#textFieldEventPolicy` and public getter & setter, but `Spinner$TextFieldEventPolicy` is package private and thus noone can use it outside of a library.

**Comment by kotcrab** [comment]
Oops, fixed in https://github.com/kotcrab/vis-editor/commit/95976508f29db6f624f69d6b41b205a6cbb85db3. Thanks for reporting.
