### ISSUE TITLE
[VisUI] SubMenu may be out of the screen if it larger then stage's width

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#220]
I encountered with pretty strange behavior, once my `SubMenu` is no longer visible anymore. Then I noticed that problem occurs only if there is not enough width for submenu.

So here is a code that resposible for the situation `MenuItem#showSubMenu()`:
```java
Vector2 pos = localToStageCoordinates(tmpVector.setZero());

float subMenuX;
if (pos.x + getWidth() + subMenu.getWidth() >= stage.getWidth()) { //if won't fit on screen
    subMenuX = pos.x - subMenu.getWidth() + 1;
} else {
    subMenuX = pos.x + getWidth() - 1;
}
subMenu.setPosition(subMenuX, pos.y - subMenu.getHeight() + getHeight());
```

It looks very strange, because it always places `SubMenu` to the left to `MenuItem`, and in most cases it could be even worse then displaying only portion to the right. For example, my `MenuItem` at the most left corner of a screen, and screen width is less then `SubMenu`'s width. So we've got `SubMenu` completely out of the screen.

Perhaps this conditional check must be a little bit more complicate, it should check whether it's better to display submenu to the left or right to parent menu and has an addition special case when there is not enough width, then act somehow very specific, like place submenu to the most left corner of a screen.

**Comment by metaphore** [comment]
It's 1.2.3 and you referenced exact that cahnge that stands for current issue

**Comment by kotcrab** [comment]
For me, it wasn't working before this change. Please provide [SSCCE](http://sscce.org/).

That `if` places submenu to the left if there isn't enough space to fully display submenu on the right. The version before doesn't make sense because it uses width of current `MenuItem` to offset submenu to the right, I don't really know why it was working before, probably when I was testing I used menus width same width.

**Comment by metaphore** [comment]
Perhaps this gif will be enough to demonstrate the issue:

![Alt Text](http://i.imgur.com/SVY10AV.gif)

**Comment by kotcrab** [comment]
Yep this explains it, it's working as intended: not enough space on the right so it displays on the left. Too bad there is 0 available space on the left. I will make it always prefer side that has more available space.

**Comment by kotcrab** [comment]
Done, thanks for reporting.
