### ISSUE TITLE
MultiSplitPane does not feature setWidgets method supporting iterables/collections

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#221]
Arrays are awkward to manage in pure Java - in many cases, it would be much more convenient to set `MultiSplitPane` children using a method like `#setWidgets(Iterable<Actor> widgets)`. Currently only arrays are supported.

**Comment by kotcrab** [comment]
It's varargs so you can do `splitPane.setWidgets(label, label2, label3);` but yeah that method won't hurt.

**Comment by czyzby** [comment]
But you don't always know the exact amount of widgets you're going to use and collections are much more flexible for that.
