### ISSUE TITLE
Crash when i open scene by editor version 0.3.4-20160924

### ISSUE THREAD

**Issue by itsabhiaryan** [kotcrab/vis-editor#223]
I am not new with visEditor, But yesterday i downloaded latest version and editor got crashed when i open newly created scene.

**Comment by kotcrab** [comment]
Please provide crash report. Help -> About -> Open App Data Folder -> check `logs` folder.

**Comment by itsabhiaryan** [comment]
Here is the : 
[viseditor-crash 16-10-12 22-58-02.txt](https://github.com/kotcrab/vis-editor/files/525283/viseditor-crash.16-10-12.22-58-02.txt)

**Comment by kotcrab** [comment]
Sorry, some issue occurred during compilation of 0.3.4 version which caused one class to be missing... I recompiled it, please try [this build](http://dl.kotcrab.com/vis/editor/content/VisEditor-0.3.4-r2.zip). Thanks for reporting.

**Comment by itsabhiaryan** [comment]
No problem, Thanks for the awesome library.
