### ISSUE TITLE
No disable method in Spinner

### ISSUE THREAD

**Issue by Snehks** [kotcrab/vis-editor#229]
Hi kotcrab, firstly thanks for this amazing extension. This surely has made my life easier :)

I am currently using a Spinner in my UI and I want to disable it during some events, but it doesn't expose any public method to do so. I thought of extending the class and overriding some stuff but realized that won't work.

Is there any way to disable it? If not then it will be really useful to have it. I can fork the repo and try to submit a pull request if you want. All we need is to make the button table and input model as fields in class and disable them but I am not sure.

**Comment by kotcrab** [comment]
Hey, thanks!

It isn't possible now but should be very simple to add. Disable method should just call disable on text field and two buttons like you noticed. You are very welcome to send a PR for this. Don't forget about adding equivalent `isDisabled`. Also no need for adding TextField field though, you can use `getTextField`.

**Comment by kotcrab** [comment]
Thanks!

**Comment by Snehks** [comment]
No problems. Again thanks for this amazing library. 👍
