### ISSUE TITLE
Feature Request : TextArea with coloured strings support

### ISSUE THREAD

**Issue by Snehks** [kotcrab/vis-editor#231]
Hi Kotcrab,

I was wondering if its possible for VisUI to have TextArea extension which allows us to append text with the colour we want. Like appendText(String text, Color color). This will be a really good feature to have because it is a pain if we want to add different coloured text lines inside text area. We have HightlightTextArea but I don't think it solves the purpose.

Thanks.

**Comment by kotcrab** [comment]
I'm not sure if this can be implemented in reliable manner. You see, showing coloured text is not a problem but letting user edit text is. It's not possible to embed colours tags in text because because user could overwrite them and text area can't handle text that has some part invisible at all. I'm not seeing any solution for this. `HightlightTextArea` works completely different as it uses parser to determinate colours so after editing text it can be just reparsed.

**Comment by Snehks** [comment]
All right then.. Not sure how to achieve this because in my application I have chatbox in which I want to have separate colors for different types of user (Text by Admin has a different color, Text by Donator has a different etc).

But no worries, I will see if I could do something with HighlightTextArea. Thanks.

**Comment by kotcrab** [comment]
Why would you use text area for chatbox? It usually isn't editable text and if it's not editable you can use simple coloured labels or labels with libGDX's colour markup language.

**Comment by Snehks** [comment]
I didn't think about that to be honest :) I can give it a try I just felt creating labels for every message will be too much. Also I am not sure how exactly I will do it because I will need it to be scrollable and the text should be inside the bounds of chatbox etc etc. 

For time being I solved my purpose using HighlightTextArea as in my particular game I pass tags in chat for different type of user levels. I used them to set colors. It works fine but I will give the label idea a go someday.

**Comment by kotcrab** [comment]
Labels probably wouldn't be too much, at some point you will have to clear old messages anyways. If I membered correctly text area will start having performance problems when you have about 1000 lines of text (regardless if highlighting is used or not).
