### ISSUE TITLE
Horizontal CollapsibleWidget

### ISSUE THREAD

**Issue by nathanhack** [kotcrab/vis-editor#232]
The CollapsibleWidget is only collapsible in the vertical direction. 

Feature request: to make CollapsibleWidget able to support horizontal collapsing.

**Comment by nathanhack** [comment]
Here's an example of what I'm talking about :-) 



`

public class VHCollapsibleWidget extends WidgetGroup {
    private boolean horizontal;
    private Table table;

    private CollapseAction collapseAction = new CollapseAction();

    private boolean collapsed;
    private boolean actionRunning;

    private float currentHeight;
    private float currentWidth;

    public VHCollapsibleWidget() {
    }

    public VHCollapsibleWidget(Table table, boolean horizontal) {
        this(table, horizontal, false);
    }

    public VHCollapsibleWidget(Table table, boolean horizontal, boolean collapsed) {
        this.collapsed = collapsed;
        this.table = table;
        this.horizontal = horizontal;

        updateTouchable();

        if (table != null) addActor(table);
    }

    public void setCollapsed(boolean collapse, boolean withAnimation) {
        this.collapsed = collapse;
        updateTouchable();

        if (table == null) return;

        actionRunning = true;

        if (withAnimation) {
            addAction(collapseAction);
        } else {
            if (horizontal) {
                if (collapse) {
                    currentWidth = 0;
                    collapsed = true;
                } else {
                    currentWidth = table.getPrefWidth();
                    collapsed = false;
                }
            } else {
                if (collapse) {
                    currentHeight = 0;
                    collapsed = true;
                } else {
                    currentHeight = table.getPrefHeight();
                    collapsed = false;
                }
            }
            actionRunning = false;
            invalidateHierarchy();
        }
    }

    public void setCollapsed(boolean collapse) {
        setCollapsed(collapse, true);
    }

    public boolean isCollapsed() {
        return collapsed;
    }

    private void updateTouchable() {
        if (collapsed)
            setTouchable(Touchable.disabled);
        else
            setTouchable(Touchable.enabled);
    }

    @Override
    public void draw(Batch batch, float parentAlpha) {
        if (horizontal) {
            if (currentWidth > 1) {
                batch.flush();
                boolean clipEnabled = clipBegin(getX(), getY(), currentWidth, getHeight());

                super.draw(batch, parentAlpha);

                batch.flush();
                if (clipEnabled) clipEnd();
            }
        } else {
            if (currentHeight > 1) {
                batch.flush();
                boolean clipEnabled = clipBegin(getX(), getY(), getWidth(), currentHeight);

                super.draw(batch, parentAlpha);

                batch.flush();
                if (clipEnabled) clipEnd();
            }
        }
    }

    @Override
    public void layout() {
        if (table == null) return;

        table.setBounds(0, 0, table.getPrefWidth(), table.getPrefHeight());

        if (actionRunning == false) {
            if (horizontal) {
                if (collapsed)
                    currentWidth = 0;
                else
                    currentWidth = table.getPrefWidth();
            } else {
                if (collapsed)
                    currentHeight = 0;
                else
                    currentHeight = table.getPrefHeight();
            }
        }
    }

    @Override
    public float getPrefWidth() {
        if (table == null) return 0;

        if (horizontal) {
            if (actionRunning == false) {
                if (collapsed)
                    return 0;
                else
                    return table.getPrefWidth();
            }

            return currentWidth;
        } else {
            return table.getPrefWidth();
        }
    }

    @Override
    public float getPrefHeight() {
        if (table == null) return 0;

        if (horizontal) {
            return table.getPrefHeight();
        } else {
            if (actionRunning == false) {
                if (collapsed)
                    return 0;
                else
                    return table.getPrefHeight();
            }

            return currentHeight;
        }
    }

    public void setTable(Table table) {
        this.table = table;
        clearChildren();
        addActor(table);
    }

    @Override
    protected void childrenChanged() {
        super.childrenChanged();
        if (getChildren().size > 1)
            throw new GdxRuntimeException("Only one actor can be added to CollapsibleWidget");
    }

    private class CollapseAction extends Action {
        @Override
        public boolean act(float delta) {
            if (horizontal) {
                if (collapsed) {
                    currentWidth -= delta * 1000;
                    if (currentWidth <= 0) {
                        currentWidth = 0;
                        collapsed = true;
                        actionRunning = false;
                    }
                } else {
                    currentWidth += delta * 1000;
                    if (currentWidth > table.getPrefWidth()) {
                        currentWidth = table.getPrefWidth();
                        collapsed = false;
                        actionRunning = false;
                    }
                }
            } else {
                if (collapsed) {
                    currentHeight -= delta * 1000;
                    if (currentHeight <= 0) {
                        currentHeight = 0;
                        collapsed = true;
                        actionRunning = false;
                    }
                } else {
                    currentHeight += delta * 1000;
                    if (currentHeight > table.getPrefHeight()) {
                        currentHeight = table.getPrefHeight();
                        collapsed = false;
                        actionRunning = false;
                    }
                }
            }

            invalidateHierarchy();
            return !actionRunning;
        }
    }
}
`

**Comment by kotcrab** [comment]
Thanks, I opted for separate class since that leads to less complex constructor invocation without breaking APIs.
