### ISSUE TITLE
Vis-UI: Doesn't show mapped network drives

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#235]
I used to see mapped network drives, however I no longer see them: 
![image](https://cloud.githubusercontent.com/assets/567688/21039525/be14a73a-bd9b-11e6-9015-c1e0871970db.png)

This is on Windows 10, confirmed on multiple computers. Using Vis-UI 1.2.5-SNAPSHOT (the drive was mapped before the application was ever launched. I recall that this used to work, or at least it did from a Windows 7 host, but I don't have easy access to my Windows 7 machine at the moment.

**Comment by kotcrab** [comment]
I don't have any network drive so I can't test this at all. Would be great if you could try older version that you are sure was working on Windows 7. In general it's using Java's `File.getRoots()` so if that doesn't return the drive I'm afraid there isn't anything I can do.

**Comment by bruceloco** [comment]
Are you running the program from a different user's context? like "run as administrator"
java can only see the context from the user

**Comment by WickedShell** [comment]
This appears to be intermittently working, for whatever reason I have to have explicitly touched the networked drive with windows explorer (or equivalent) before Java can acknowledge it. I'm inclined to say this is a windows/java problem rather then a vis-ui issue.
