### ISSUE TITLE
Gdx 1.9.5 GWT 2.8.0 compatibility error.

### ISSUE THREAD

**Issue by piotr-j** [kotcrab/vis-editor#237]
Due to updated gwt, java.lang.System is no longer emulated on gdx side. This causes `System.getProperty("os.name")` call to fail in `com.kotcrab.vis.ui.util.OsUtils` due to only the getProperty with default value being implemented. Updating the call to `System.getProperty("os.name", "")` fixes the issue. 

https://github.com/kotcrab/vis-editor/blob/master/ui/src/main/java/com/kotcrab/vis/ui/util/OsUtils.java#L29

**Comment by kotcrab** [comment]
Thanks!

**Comment by bruynca** [comment]
When I try to run HTML on my project getting following error:

Compiling module brnsft.on.ca.GdxDefinitionSuperdev
   [ERROR] Errors in 'com/kotcrab/vis/ui/util/OsUtils.java'
      [ERROR] Line 29: The method getProperty(String) in the type System is not applicable for the arguments (String, String)
:html:draftCompileGwt FAILED


BUILD FAILED

**Comment by kotcrab** [comment]
Interesting, did they change it to version without second argument?

@bruynca what version of VisUI and libGDX are you using?

**Comment by bruynca** [comment]
From  my gradle build file:


allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = "WinterThunder"
        gdxVersion = '1.9.3'
        roboVMVersion = '1.12.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
	visuiVersion = '1.2.5'
    }

**Comment by bruynca** [comment]
Reverted to previous version:


  version = '1.0'
    ext {
        appName = "WinterThunder"
        gdxVersion = '1.9.3'
        roboVMVersion = '1.12.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
		visuiVersion = '1.1.6'
    }

HTML works.

**Comment by kotcrab** [comment]
Can't reproduce with latest libgdx 1.9.6, VisUI 1.3.0 and GWT 2.8.0, you are using old versions so please update. Gwt was broken in some libgdx version IIRC.
