### ISSUE TITLE
VisUI Won't Compile with GWT

### ISSUE THREAD

**Issue by madigan** [kotcrab/vis-editor#238]
When I run "./gradlew html:build", the GWT compilation fails:
```
:html:compileGwt
Compiling module tech.otter.merchant.GdxDefinition
   Tracing compile failure path for type 'com.kotcrab.vis.ui.util.async.AsyncTask'
      [ERROR] Errors in 'com/kotcrab/vis/ui/util/async/AsyncTask.java'
         [ERROR] Line 46: The constructor Thread(new Runnable(){}, String) is undefined
         [ERROR] Line 51: The method start() is undefined for the type Thread
   [ERROR] Aborting compile due to errors in some input files
```

I believe this is because GWT doesn't support the Thread class. I am using VisUI version 1.3.0-SNAPSHOT to maintain compatibility with libGDX 1.9.5. After doing some reading, it sounds like this was probably caused by #174 

Would it be feasible to use something that is GWT compatible or move this back to the editor package?

**Comment by kotcrab** [comment]
Sorry for the delay, I removed it from GWT compilation. Btw you will probably have to use next libgdx snapshot as GWT is broken in 1.9.5 anyways: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=24379
