### ISSUE TITLE
VisUI static context and different skins

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#239]
I have a usecase when I need to switch VisUI skin depending on current application screen. `VisUI` class manages static skin reference for all VisUI widgets globally and can be reloaded with new skin simply. But problem is `VisUI` should be disposed, and this will dispose previous used skin, but I need to keep it for further usage.

I have check `VisUI#skin` usage and seems like it's never used in static scopes, which means that field can be simply reassigned and everything should work well. Or at least there should be a way to dispose `VisUI` and keep foreign skin intact.

**Comment by kotcrab** [comment]
I added method to dispose `VisUI` without disposing skin itself, this just really clears private `skin` field so load can be called again.

Indeed VisUI widgets obtain skin from their constructors and it's not used later so it should be safe to change skin this way.

**Comment by metaphore** [comment]
Awesome! Thanks a lot!
