### ISSUE TITLE
resizing on OSX is broken

### ISSUE THREAD

**Issue by bruceloco** [kotcrab/vis-editor#243]
If using both lwjgl or jglfw if I don't load a project, the menus resize fine.
As soon as I have a project loaded, resizing is not working properly, resizing up shrinks the window, resizing down hides the menus
suspecting it is using project height/width, and I don't see scroll bars anywhere

**Comment by kotcrab** [comment]
This project uses lwjgl3, not lwjgl nor jglfw. Did you modify source code? On what version have you tested it? Show screenshots. This seems unrelated to OS version and can't be reproduced on Windows 10.

**Comment by bruceloco** [comment]
wrong project
