### ISSUE TITLE
[VisUI] VisImageButton#generateDisabledImage feature for VisImageTextButton

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#259]
Both `VisImageButton` and `VisImageTextButton` have pretty the same `#updateImage()` code, but `VisImageButton` supports image tinting when it's in a disabled state (`VisImageButton#generateDisabledImage` flag). It would be just awesome to provide same functionality for `VisImageTextButton`.

**Comment by kotcrab** [comment]
Agree, added. The method name is kind of silly though.
