### ISSUE TITLE
Move VisUI to separately maintained project

### ISSUE THREAD

**Issue by ericnondahl** [kotcrab/vis-editor#261]
Hi,
I'd like to propose splitting off VisUI into a separately maintained repo so that the workspace and documentation can be focused on maintaining that library.

I recently watched a dev who was making a small change to VisUI deal with compile issues in a deprecated part of the VisEditor workspace - the VisEditor projects add complexity to the workspace when just making VisUI changes.

Here are the benefits I see from creating a VisUI project:
* Clarify which pieces of this project are maintained so people don't see deprecated warnings and avoid contributing
* Enable working in a clean workspace that only has the dependencies and complexity level that VisUI requires

We can fork the repo, clean it up and host it if that would be helpful - but we'd like to follow however Kotcrab would like to clean this up, since he has put so much effort into this project :)

**Comment by kotcrab** [comment]
Moving to separate project is not going to happen. Instead I have a different solution, I've modified Gradle build files to allow easily disabling VisEditor modules and only leave UI and USL modules active. 

In `settings.gradle` you can set `visuiOnly` to `true` and VisEditor modules won't be imported. The files are still there but IDE won't recognize them as belonging to any module so they won't be indexed and analysed. They won't emit any warnings during build. Set it to false and everything is like the old way. I've made true the default.

> Clarify which pieces of this project are maintained so people don't see deprecated warnings and avoid contributing

That is partially fulfilled, not maintained modules are not recognized by IDE.

> Enable working in a clean workspace that only has the dependencies and complexity level that VisUI requires

That is fully fulfilled. `visuiOnly` mode won't download VisEditor dependencies or compile anything from it. 

I think this works pretty well as solution without splitting this repository.  In Intellij IDEA I can change `visuiOnly` variable without reimporting project, Gradle refresh is enough to update everything and recognize old modules.

**Comment by ericnondahl** [comment]
Seems like a good compromise, we'll be using that option for sure. May still be a good idea to update some of the documentation like the main readme to reference that. Thanks!
