### ISSUE TITLE
FileChooser: paste file name to text field with non-empty selection

### ISSUE THREAD

**Issue by code-disaster** [kotcrab/vis-editor#262]
tested with VisUI 1.2.5

- open FileChooser in save mode
- select an existing item (per UI, or as we do, with setSelectedFiles())
- use CTRL+V to paste a new file name into text field
- hit ENTER or click OK
- observe file overwrite warning

I believe this happens because selectedFileTextField doesn't listen for ChangeEvents, so on c&p it doesn't clear the existing selection.

**Comment by kotcrab** [comment]
Thanks for the report! Sorry it took so long but I must've missed GitHub notification.

This also affected open mode in similar way (not updated file list was passed to listeners).

Also fixed update issue with file name suggestion menu in https://github.com/kotcrab/vis-editor/commit/ec72b414d5b5e6e07547e2fe7f2221fa687ce786
