### ISSUE TITLE
X2 UI is not enough for mobile

### ISSUE THREAD

**Issue by jduke32** [kotcrab/vis-editor#263]
Hello , i have tried X2 but its not enough for mobile.Especially
FileChooser cant be seen on android devices.

VisUI.load( VisUI.SkinScale.X2 );

How can i make more scale like X4  ?

**Comment by kotcrab** [comment]
Duplicate of https://github.com/kotcrab/vis-editor/issues/226

`FileChooser` is a desktop platform only widget. You can't use it on Android.
