### ISSUE TITLE
lack of font chars

### ISSUE THREAD

**Issue by jduke32** [kotcrab/vis-editor#264]
Hello i've tried to write some texts inside your visui.
But i have seen there are some lack of chars avalible for  vis-editor.

I try to fix with adding
"ÜĞŞİÇÖüğşıçö" chars to
ui\assets-raw\x2-fonts\default.hiero
and
ui\assets-raw\x2-fonts\font-small.hiero

glyph.text=ABCDEFGHIJKLMNOPQRSTUVWXYZ\nabcdefghijklmnopqrstuvwxyzÜĞŞİÇÖüğşıçö\n1234567890•\n"!`?¿'.,;:()[]{}<>|/@\^$-%+=#_&~*\nñÑąćęłńóśźżĄĆĘŁŃÓŚŹŻÄäÖöÜüß\náéíóúàèìòùÁÉÍÓÚÀÈÌÒÙ\nАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ\nабвгдеёжзийклмнопрстуфхцчшщъыьэюя\nΑΆΒΓΔΕΈΖΗΉΘΙΊΚΛΜΝΞΟΌΠΡΣΤΥΎΦΧΨΩΏ·\nαάβγδεέζηήθιίκλμνξοόπρστυύφχψωώ\nϊΐςϋΰ⌘⌥⇧

hope new patch will help

**Comment by kotcrab** [comment]
ÜÖ are present already as part of German diacritic set.

What language will this cover? Are they any more diacritic characters from it?

**Comment by jduke32** [comment]
Its turkish lang
http://www.omniglot.com/images/writing/turkish_latin.gif

**Comment by kotcrab** [comment]
Sounds good, added.

![2017-09-01_20-01-35_6slmqn](https://user-images.githubusercontent.com/4594081/29982290-6b9dec7c-8f51-11e7-9bd4-254f63630c15.png)
