### ISSUE TITLE
For X4 we need X2's resources

### ISSUE THREAD

**Issue by eix128** [kotcrab/vis-editor#267]
Hello for X4 we need files: 
vis-ui.svg
uiskin.atlas 
These files vis-ui.svg is empty when we look inside

vis-ui.svg
version https://git-lfs.github.com/spec/v1
oid sha256:976840c331b93c46fc3afecb99849d387b03ee4abf908c56ea8ba8a880096a09
size 247306

But this is not a svg file for expanding to X4 !?

for X4 and X8 development.
We can help you for development for this editor.
Then you can also use X4 and X8

**Comment by kotcrab** [comment]
[Download](https://github.com/kotcrab/vis-editor/raw/master/ui/assets-raw/vis-ui.svg) it and open in Inkscape. (right click and save as). Browser can't handle it for some reason.

Like I said before I don't want X4 and X8 here, not with current workflow. 

Please stop creating multiple issues about the same thing. #265 #263 #226
