### ISSUE TITLE
X4 , X6 , X8 for you

### ISSUE THREAD

**Issue by eix128** [kotcrab/vis-editor#268]
https://www.dropbox.com/s/ewgjoxy1y71qsjy/pack.rar?dl=0

**Comment by kotcrab** [comment]
Why did you create separate issue for this? We already have #267 #265 #263 #226 of which 3 created by you.
I said multiple times that I don't want more skin sizes in core repository.
On top of that the link you provided does not even work with 404 error.
If you continue creating multiple issues like this I'll have to block you, this is my final warning.
