### ISSUE TITLE
FileChooser could not be used properly on Android

### ISSUE THREAD

**Issue by Tokenyet** [kotcrab/vis-editor#269]
VisUi is great and it works well on Desktop, but for Android, I got the strange FileChooser dialog that show nothing and keep loading.
For deeply debugging, I found that FileChooser pass my existed directory that returned by `Gdx.files.getExternalStoragePath()`.
The following image shows what I'm said...
![image](https://user-images.githubusercontent.com/6420527/30426320-332e6420-997e-11e7-9525-1b3ff160adb8.png)

And I got this: 
![image](https://user-images.githubusercontent.com/6420527/30426525-f52bd7b0-997e-11e7-958c-121b75e8a18e.png)

But the code could work well on Bluestacks but not for ADB emulator and My Phone, the code I used:

       final Stage stage = getStage();
        FileChooser.setDefaultPrefsName("my.package.filechooser");
        if(fileChooser == null) {
            fileChooser = new FileChooser(FileChooser.Mode.OPEN);
        }
        fileChooser.setFillParent(true);
        FileTypeFilter typeFilter = new FileTypeFilter(true); //allow "All Types" mode where all files are shown
        typeFilter.addRule("Image files (*.png, *.jpg, *.gif)", "png", "jpg", "gif");
        fileChooser.setFileTypeFilter(typeFilter);
        fileChooser.setDirectory(Gdx.files.getExternalStoragePath());
        fileChooser.setSelectionMode(FileChooser.SelectionMode.FILES);
        fileChooser.addAction(Actions.moveTo(0, 100));
        fileChooser.setListener(new FileChooserAdapter() {
            @Override
            public void selected (Array<FileHandle> file) {
                fileChooser.fadeOut();
            }

            @Override
            public void canceled() {
                fileChooser.fadeOut();
                super.canceled();
            }
        });
        if(!stage.getActors().contains(fileChooser, false))
            stage.addActor(fileChooser);
        fileChooser.fadeIn();

Hope someone could help me out :(

Update(2017-09-14):
It works when I debugging step by step (following snapshot). But after end of few steps, it turn back to empty page.
![image](https://user-images.githubusercontent.com/6420527/30427319-ee36c962-9981-11e7-85ac-8f93184e4566.png)

**Comment by kotcrab** [comment]
File chooser can't be used on Android. It's surprising you can actually see a file list at some point. Nonetheless it's not implemented with Android in mind at all.

https://github.com/kotcrab/vis-editor/wiki/File-chooser
> Chooser is platform dependent and can be only used on desktop.
