### ISSUE TITLE
ColorPicker Sizing

### ISSUE THREAD

**Issue by Tokenyet** [kotcrab/vis-editor#270]
I change the default style.json and integrate with FreetypeGenerator, but there is a problem. If I use a big size font, the UI could not be changed, even If `setWidth`, the layout of ColorPicker seems to be the same.

Hope there is a solution for ColorPicker :(
This is the only widget that works bad with FreetypeFont :(

![image](https://user-images.githubusercontent.com/6420527/31078634-80888fda-a7b5-11e7-87d8-d5d76dda90fa.png)

I found that `BasicColorPicker` size is locked also, so I could not change it by sizing :(

**Comment by kotcrab** [comment]
Have you tried changing Sizes#scaleFactor in your skin.json/usl? Or just generally using X2 Sizes preset.

**Comment by Tokenyet** [comment]
@kotcrab, That works! But are there anything also affected by `Sizes#scaleFactor` ? I'm afraid I just want the `ColorPicker` works expected but other things are going wrong.

**Comment by kotcrab** [comment]
It does affect few other widgets (`DetailsDialog`, `FileChooser` and `TabbedPane`) but it was added specifically for bigger font for x2 skin so you should be fine.

**Comment by kotcrab** [comment]
I'm going to close this since it looks like this issue was resolved.
