### ISSUE TITLE
VisTable doesnt work

### ISSUE THREAD

**Issue by JuKu** [kotcrab/vis-editor#284]
VisTable doesnt work for me, seperators aren't on right position (under text).

![ls](https://user-images.githubusercontent.com/1138046/34650277-b5dc2bec-f3be-11e7-827c-9563c25cf238.PNG)

Code:
```java
@Override
protected VisTable createView(Server proxyServer) {
        VisLabel label = new VisLabel(proxyServer.getName());
        VisLabel channelLabel = new VisLabel(proxyServer.getChannel());

        VisTable table = new VisTable();
        table.left();
        table.add(label);
        table.left();
        table.addSeparator();
        table.add(channelLabel);
        return table;
}
```

Can you help me, please?

**Comment by czyzby** [comment]
Pretty sure you have to call `pack()` on the table.

**Comment by JuKu** [comment]
@czyzby You mean ```pack()``` after ```table.add(channelLabel)```?

```java
@Override
protected VisTable createView(Server proxyServer) {
        VisLabel label = new VisLabel(proxyServer.getName());
        VisLabel channelLabel = new VisLabel(proxyServer.getChannel());

        VisTable table = new VisTable();
        table.left();
        table.add(label);
        table.left();
        table.addSeparator();
        table.add(channelLabel);
        table.pack();
        return table;
}
```

Or when is a pack() required?

**Comment by czyzby** [comment]
I think you have to call `pack()` once on the main widget after adding all secondary widgets. So you can either call it the way you posted or on your table's parent. Beside, now that I look at your code, it seems that you're not calling `row()` after adding labels, which would make the separator go under the text. Also, look into `colspan` cell setting when playing with rows. Maybe you should read a Scene2D tutorial before using VisUI.

**Comment by kotcrab** [comment]
`addSeparator()` does call `row()` after adding horizontal separator, not before it.
