### ISSUE TITLE
Is it possible to change the font?

### ISSUE THREAD

**Issue by Seref** [kotcrab/vis-editor#295]
Hey there is there a way to change the default font?

I wasn't able to overwrite/change the original bitmapfont by using

```
skin.add("default-font", generator.generateFont(parameter), BitmapFont.class);
skin.add("small-font", generator.generateFont(parameter), BitmapFont.class);
```
and then reloading the Visui.

Is there a way?

**Comment by EtK2000** [comment]
You can change it like that only before the individual default styles are instantiated.

What you can do is either:
Actor.getStyle().font = font;
or get the style from the skin directly.

Also, I just want to point out 2 things:
1. This isn't Vis related, it's LibGDX
2. This shouldn't be an issue, please next time ask on forums or in irc.
