### ISSUE TITLE
Can't build signed release apk for Android

### ISSUE THREAD

**Issue by fmmarzoa** [kotcrab/vis-editor#296]
The problem seems to be this:
Warning: com.kotcrab.vis.ui.widget.file.FileUtils: can't find referenced class com.apple.eio.FileManager

Using libGDX 1.9.9-SNAPSHOT and VisUI 1.4.2-SNAPSHOT

**Comment by fmmarzoa** [comment]
I solved this by adding a 

-dontwarn com.apple.eio.FileManager

to my proguard rules.

**Comment by kotcrab** [comment]
You will probably want to disable proguard for VisUI and libgdx classes. At the very least you will need to add rules to skip Skin and UI styles classes because they are instantiated through reflection after loading skin json.
