### ISSUE TITLE
Box2dLights support

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-editor#43]
General list of things needs to be done:
- [ ] LightComponent
- [ ] Runtime systems
- [ ] Light settings dialog
  - [ ] SceneDeserializer: bump version code and handle null light settings data
- [ ] Lighting switch button on toolbar
- [ ] Creating point light
- [ ] Creating cone light

**Comment by dmitrypotenko** [comment]
Hi!
I found that i really need this support for my project. It will be really cool if you solve this.

**Comment by kotcrab** [comment]
Sorry, this is not going to happen. VisEditor is deprecated now. [Some more info](https://kotcrab.com/blog/2017/03/26/visui-130-released-viseditor-deprecated/).
