### ISSUE TITLE
Editor ninepatch support

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-editor#69]
Feature request: http://forum.kotcrab.com/d/5-9-patch-images-support

**Comment by dmitrypotenko** [comment]
Hi.
I hope you will added this in near future). I am java developer too, so feel free to ask if i can help you in developing your amazing tool)

**Comment by kotcrab** [comment]
Sorry, this is not going to happen. VisEditor is deprecated now. [Some more info](https://kotcrab.com/blog/2017/03/26/visui-130-released-viseditor-deprecated/).
