### ISSUE TITLE
Lock origin field when "Auto Adjust Origin" in PhysicsPropertiesComponent is checked

### ISSUE THREAD

**Issue by UvarovBoris** [kotcrab/vis-editor#90]
Hi, origin of actor with physics component always zero and cant be modified.
Version of VisEditor  2.6.0-SNAPSHOT 20151206-1

**Comment by kotcrab** [comment]
This is actually intended, origin needs to be set to (0, 0) if you are using physics with sprites or you will get incorrect sprite placement when body is rotated. You can disable this by unchecking "Auto Adjust Origin" in `PhysicsPropertiesComponent`
![2015-12-07_2055](https://cloud.githubusercontent.com/assets/4594081/11638001/de159c62-9d24-11e5-97a3-e469ede4825f.png)

I must say this is not intuitive so I will change this issue to enhancement and add some mark in UI to notify that origin is locked when that field is checked.
